name: Add member to team version 2
on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub username of the new member'
        required: true
        type: string
jobs:
  add_member:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: write username
        run: |
          echo "${{ inputs.username }}"

      - name: add user to team
        id: add-user
        run: |
          echo ${{ secrets.READ_WRITE }} | gh auth login --hostname github.com --with-token
          gh auth status
          gh api --method PUT -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/V-DEF/teams/reader/memberships/Normtronic -f role='maintainer' 