name: Add user to team

on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub username of the new member'
        required: true
        type: string

jobs:
  validate-issue:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: write username
        run: |
          echo "${{ inputs.username }}"

      - name: add user to team
        id: add-user
        run: |
          echo ${{ secrets.READ_WRITE }} | gh auth login --hostname github.com --with-token
          gh auth status
          gh api --method PUT -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/V-DEF/teams/user/memberships/Normtronic -f role='maintainer' 