name: Check Team Membership

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub username to check'
        required: true
        type: string

jobs:
  check_membership:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check team membership
      env:
        GH_TOKEN: ${{ secrets.READ_WRITE }}
        ORG_NAME: V-DEF
        TEAM_SLUG: reader
        USERNAME: ${{ github.event.inputs.username }}
      run: |
        echo "Checking if user $USERNAME is a member of team $TEAM_SLUG in organization $ORG_NAME"
        response=$(curl -s -H "Authorization: token $GH_TOKEN" \
                          -H "Accept: application/vnd.github.v3+json" \
                          https://api.github.com/orgs/$ORG_NAME/teams/$TEAM_SLUG/memberships/$USERNAME)
        echo "API Response: $response"
        if echo "$response" | jq -e '.state == "active"' > /dev/null; then
          echo "User $USERNAME is a member of team $TEAM_SLUG."
        else
          echo "User $USERNAME is NOT a member of team $TEAM_SLUG."
          exit 1
        fi