name: Create Issue

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the issue'
        required: true
        type: string
      body:
        description: 'Body of the issue'
        required: true
        type: string

jobs:
  create_issue:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create GitHub Issue
      env:
        GH_TOKEN: ${{ secrets.READ_WRITE }}
        ORG_NAME: V-DEF
        REPO_NAME: public_workflow_test
        ISSUE_TITLE: ${{ github.event.inputs.title }}
        ISSUE_BODY: ${{ github.event.inputs.body }}
      run: |
        echo "Creating issue in repository: $ORG_NAME/$REPO_NAME"
        response=$(curl -s -X POST -H "Authorization: token $GH_TOKEN" \
                          -H "Accept: application/vnd.github.v3+json" \
                          https://api.github.com/repos/$ORG_NAME/$REPO_NAME/issues \
                          -d "{\"title\":\"$ISSUE_TITLE\", \"body\":\"$ISSUE_BODY\"}")
        echo "API Response: $response"
        if echo "$response" | jq -e '.id' > /dev/null; then
          echo "Issue created successfully."
        else
          echo "Failed to create issue."
          exit 1
        fi