name: TEST

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
